# Generated by Django 3.2.5 on 2021-09-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0002_auto_20210906_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charity',
            old_name='userID',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='charity',
            name='city',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='charity',
            name='speciality',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Speciality',
        ),
    ]
