# Generated by Django 3.2.5 on 2021-09-06 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0003_auto_20210906_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=64)),
            ],
        ),
        migrations.RenameField(
            model_name='charity',
            old_name='username',
            new_name='userID',
        ),
        migrations.AlterField(
            model_name='charity',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charity.city'),
        ),
        migrations.AlterField(
            model_name='charity',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charity.speciality'),
        ),
    ]
