# Generated by Django 3.2.5 on 2021-09-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0004_auto_20210906_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activateCode',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='activeState',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
