# Generated by Django 3.2.5 on 2021-09-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0005_auto_20210907_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='slogan',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
