# Generated by Django 3.2.5 on 2021-09-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0006_alter_charity_slogan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='slogan',
            field=models.ImageField(blank=True, upload_to='slogan'),
        ),
    ]
