# Generated by Django 3.2.5 on 2021-09-09 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0010_onetimelinkmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activateCode',
        ),
        migrations.RemoveField(
            model_name='user',
            name='activeState',
        ),
    ]
